apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-mlflow
spec:
  project: default
  source:
    repoURL: https://github.com/bqmxnh/cloud-ops.git
    targetRevision: main
    path: values/mlflow

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
