FROM python:3.10-slim

WORKDIR /app

# System deps
RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

# Python deps + DVC
COPY retrain/requirements.retrain_arf.txt .
RUN pip install --no-cache-dir \
    -r requirements.retrain_arf.txt \
    dvc[s3]

# Copy code & datasets (TỪ ROOT CONTEXT)
COPY retrain/ /app/retrain/
COPY datasets/ /app/datasets/

# Runtime dirs
RUN mkdir -p /data /output

ENTRYPOINT ["bash"]
