FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

COPY retrain/requirements.retrain_arf.txt .
RUN pip install --no-cache-dir -r requirements.retrain_arf.txt dvc[s3]

COPY retrain/ /app/retrain/
COPY datasets/base/base.csv.dvc /app/datasets/base/base.csv.dvc

RUN mkdir -p /data /output

ENTRYPOINT ["bash"]
