apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: arf-incremental-retrain
spec:
  entrypoint: main
  serviceAccountName: argo-workflows-workflow-controller

  arguments:
    parameters:
      - name: hours
        value: "24"
      - name: delta
        value: "0.002"
      - name: window
        value: "30"
      - name: min_samples
        value: "100"

  templates:

  # ============================================================
  # MAIN DAG
  # ============================================================
  - name: main
    dag:
      tasks:

      - name: check-drift
        template: check-drift

      - name: fetch-drift
        dependencies: [check-drift]
        when: "{{tasks.check-drift.outputs.parameters.drift}} == true"
        template: fetch-drift
        arguments:
          parameters:
            - name: drift_ts
              value: "{{tasks.check-drift.outputs.parameters.drift_ts}}"


      # # 3️⃣ MERGE BASE + DRIFT (7:3)
      # - name: merge-data
      #   dependencies: [fetch-drift]
      #   template: merge-data

      # # 4️⃣ PREPROCESS + SMOTE
      # - name: preprocess
      #   dependencies: [merge-data]
      #   template: preprocess

      # # 5️⃣ RETRAIN + EVALUATE (hold-out 80/20)
      # - name: retrain
      #   dependencies: [preprocess]
      #   template: retrain

  # ============================================================
  # TEMPLATE: CHECK DRIFT
  # ============================================================
  - name: check-drift
    container:
      image: bqmxnh/cloud-ops-retrain:latest
      command: ["bash", "-c"]
      args:
        - |
          echo "[STEP] CHECK DRIFT"
          python /app/retrain/check_drift.py \
            --hours {{workflow.parameters.hours}} \
            --delta {{workflow.parameters.delta}} \
            --window {{workflow.parameters.window}} \
            --min-samples {{workflow.parameters.min_samples}} \
            | tee /tmp/check.log

          if grep -q "DRIFT=true" /tmp/check.log; then
            echo "true" > /tmp/drift
            grep FIRST_DRIFT_TS /tmp/check.log | cut -d= -f2 > /tmp/drift_ts
          else
            echo "false" > /tmp/drift
          fi
    outputs:
      parameters:
        - name: drift
          valueFrom:
            path: /tmp/drift
        - name: drift_ts
          valueFrom:
            path: /tmp/drift_ts


  # ============================================================
  # TEMPLATE: FETCH DRIFT
  # ============================================================
  - name: fetch-drift
    inputs:
      parameters:
        - name: drift_ts
    container:
      image: bqmxnh/cloud-ops-retrain:latest
      command: ["bash", "-c"]
      args:
        - |
          echo "[STEP] FETCH DRIFT"
          echo "Using drift_ts={{inputs.parameters.drift_ts}}"

          python /app/retrain/fetch_drift.py \
            --drift-ts {{inputs.parameters.drift_ts}} \
            --output /data/drift_raw.csv


  # # ============================================================
  # # TEMPLATE: MERGE BASE + DRIFT
  # # ============================================================
  # - name: merge-data
  #   container:
  #     image: bqmxnh/cloud-ops-retrain:latest
  #     command: ["bash", "-c"]
  #     args:
  #       - |
  #         echo "[STEP] MERGE DATA (7:3)"
  #         python retrain/merge_data.py \
  #           --drift /data/drift_window.csv \
  #           --base /data/base.csv \
  #           --output /data/drift.csv

  # # ============================================================
  # # TEMPLATE: PREPROCESS + SMOTE
  # # ============================================================
  # - name: preprocess
  #   container:
  #     image: bqmxnh/cloud-ops-retrain:latest
  #     command: ["bash", "-c"]
  #     args:
  #       - |
  #         echo "[STEP] PREPROCESS + SMOTE"
  #         python retrain/preprocess.py \
  #           --input /data/drift.csv \
  #           --output /data/train_smote.csv

  # # ============================================================
  # # TEMPLATE: RETRAIN + HOLD-OUT EVALUATION
  # # ============================================================
  # - name: retrain
  #   container:
  #     image: bqmxnh/cloud-ops-retrain:latest
  #     resources:
  #       requests:
  #         memory: "4Gi"
  #         cpu: "1"
  #       limits:
  #         memory: "8Gi"
  #         cpu: "2"
  #     command: ["bash", "-c"]
  #     args:
  #       - |
  #         echo "[STEP] RETRAIN + EVALUATE (80/20 HOLD-OUT)"
  #         python retrain/retrain_arf.py
