apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-check-drift-
spec:
  entrypoint: check
  serviceAccountName: argo-workflows-workflow-controller

  templates:
  - name: check
    container:
      image: bqmxnh/cloud-ops-retrain:latest
      command: ["bash", "-c"]
      args:
        - |
          echo "=== RUN check_drift.py ==="
          python retrain/check_drift.py \
            --hours 24 \
            --delta 0.0002 \
            --window 30 \
            --min-samples 100

          echo "EXIT_CODE=$?"
